apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namespace: stage


# This patch will replace the image tag with "1.16.1"
patches:
- target:
    kind: Deployment
    name: nginx-deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:1.16.1
